model_parameters=list()
model_parameters$names                             =c('beta', 'mu0', 'mu1', 'sigma', 'tau0', 'tau1')
model_parameters$transformation                    =c('none', 'none', 'none', 'none', 'none', 'none')
model_parameters$artificial_population_location    =c( 4,       1,  0.25 ,   0.5,     1, 0.1)
model_parameters$artificial_population_scale       =c( 2,    0.2,   0.2,    0.1,0.2,  0.2)
