model_parameters=list()
model_parameters$names                             =c('alpha','beta', 'c')
model_parameters$transformation                    =c('logit','none', 'none')
model_parameters$artificial_population_location    =c(0.5,4, 1)
model_parameters$artificial_population_scale       =c(1,1.5, 0.25)
